---
title: "20220619_fpl"
author: "Arif P. Sulistiono / @arifpras"
date: '2022-06-19'
output: html_document
---

```{r}
# Remove all items in Environment!
rm(list = ls())
ls()

# Load packages
pacman::p_load(tidyverse, data.table, readxl, writexl, glue, wesanderson,
               RColorBrewer, viridis, ggrepel, ggthemes, ggsci, mFilter,
               quantmod, corrplot, cowplot, readstata13, readr, knitr, 
               kableExtra, stargazer, parameters, colorspace, dendextend,
               ggdendro, purrr, cluster, plotly, DescTools, factoextra, 
               grid, gridExtra, ggsoccer, RCurl, tidytext)

options(tz = "Europe/London")

# Working directory
setwd("~/OneDrive - The University of Nottingham/BB_SideProject/2022FPL")
```

```{r include=FALSE}
id_dict <- "https://raw.githubusercontent.com/arifpras/Fantasy-Premier-League/master/data/2021-22/id_dict.csv"

db00a <- readr::read_csv(id_dict)
```

```{r include=FALSE}
player_udrstat_2021 <- "https://raw.githubusercontent.com/arifpras/Fantasy-Premier-League/master/data/2020-21/understat/understat_player.csv"

player_udrstat_2122 <- "https://raw.githubusercontent.com/arifpras/Fantasy-Premier-League/master/data/2021-22/understat/understat_player.csv"

db00b <- read_csv(player_udrstat_2021)
db00c <- read_csv(player_udrstat_2122)
```

```{r include=FALSE}
player_hist_2021 <- "https://raw.githubusercontent.com/arifpras/Fantasy-Premier-League/master/data/2021-22/gws/merged_gw.csv"

player_hist_2122 <- "https://raw.githubusercontent.com/arifpras/Fantasy-Premier-League/master/data/2020-21/gws/merged_gw.csv"

db00d <- read_csv(player_hist_2021)
db00e <- read_csv(player_hist_2122)
```

```{r include=FALSE}
#season 2020/2021
db00f <- db00d %>%
  left_join(db00a, by = c("name" = "FPL_Name")) %>%
  na.omit() %>%
  mutate(kickoff_time_adj = as.Date(kickoff_time, "%Y-%m-%d"))

#season 2021/2022
db00g <- db00e %>%
  left_join(db00a, by = c("name" = "FPL_Name")) %>%
  na.omit() %>%
  mutate(kickoff_time_adj = as.Date(kickoff_time, "%Y-%m-%d"))
```

```{r include=FALSE}
#NA understat_id
db99a <- db00d %>% 
  left_join(db00a, by = c("name" = "FPL_Name")) %>% 
  filter(is.na(FPL_ID)) %>% 
  distinct(name)

db99b <- db00e %>% 
  left_join(db00a, by = c("name" = "FPL_Name")) %>% 
  filter(is.na(FPL_ID)) %>% 
  distinct(name)
```

```{r}
#Active players from mid 2021/2022
#db00h <- db00f %>% 
#  filter(kickoff_time_adj > "2022-01-31") %>%
#  group_by(name, Understat_ID) %>% 
#  summarise(
#    totminutes = sum(minutes),
#    .groups = "keep"
#  ) %>% 
#  ungroup %>% 
#  filter(totminutes != 0) %>% 
#  mutate(
#    active_mid2122 = "Yes"
#  )

relegated <- c("Burnley", "Norwich", "Watford")

(
  db00h <- db00f %>%
    filter(kickoff_time_adj > "2022-01-31") %>%
    group_by(name, Understat_ID) %>%
    mutate(totminutes = sum(minutes),
           .groups = "keep") %>%
    ungroup %>%
    filter(totminutes != 0) %>%
    mutate(active_mid2122 = "Yes") %>%
    group_by(name) %>%
    slice_head(n = 1) %>%
    ungroup() %>%
    select(name, Understat_ID, position, team, totminutes, active_mid2122) %>%
    filter(!team %in% relegated #not including the relegated teams)
    )
)
```

```{r}
#merging player stats from 20/21 and 21/22

#db00i <- db00f %>%
#  bind_rows(db00g) %>% 
#  right_join(db00h, c = "name")

(
  db00i <- db00f %>%
    bind_rows(db00g) %>%
    left_join((db00h %>% select(-position, -team)), c("name", "Understat_ID")) %>%
    filter(active_mid2122 == "Yes") %>%
    arrange(name, kickoff_time_adj, GW)
)
```

```{r}
#aggregate, player stats in two seasons
(
  db01a <- db00i %>% 
  group_by(name, Understat_ID) %>% 
  summarise(
    avg_points = mean(total_points),
    wvg_points = weighted.mean(total_points, (value/10)),    
    std_points = sd(total_points),
    avg_minutes = mean(minutes),
    avg_price = mean((value/10)),
    std_influence = sd(influence),
    .groups = "keep"
  ) %>% 
  ungroup() %>% 
  filter(
    avg_points > 2 & avg_minutes > 40
  ) %>% 
  arrange(desc(wvg_points))
)
```

```{r}
#merging understat's statistics
(
  db00j <- (db00b %>% mutate(season = "21/22")) %>%
    bind_rows(db00c %>% mutate(season = "20/21")) %>%
    arrange(player_name, season)
)
```

```{r}
#individual statistics in two seasons
(
  db00k <- db00j %>% 
  group_by(player_name, id) %>% 
  summarise(
    avg_xG = mean(xG), #expected goals
    avg_xA = mean(xA), #expected assist
    avg_npxG = mean(npxG), #non-penalty expected goals
    avg_xGChain = mean(xGChain), #number of Expected Goals in which a player has participated
    avg_xGBuildup = mean(xGBuildup), #which players are part of passing chains that end in a shot but without taking into account the last two links – shot and last pass -, thus measuring midfielders, centre-backs or full-backs who have an important influence on their team's possessions
    .groups = "keep"
  ) %>% 
  ungroup() %>% 
  right_join(
    (db00h %>% select(Understat_ID, team, position)), by = c("id" = "Understat_ID")
  )
)
```

```{r}
#merging db01a with the understat's statistics
(
  db01b <- db01a %>% 
  left_join((db00k %>% select(-player_name)), c("Understat_ID" = "id")) %>% 
  relocate(
    name, position, team
  )
)
```

```{r final-db}
(
  db01c <- db01b %>% 
  left_join(db00a %>% select(Understat_ID, Understat_Name), by = c("Understat_ID")) %>% 
  select(-name) %>% 
  relocate(
    Understat_Name, position, team
  )
)
```

```{r pivoting_by_position}
(
  db02a <- db01c %>% 
    select(Understat_Name, position) %>% 
  as_tibble() %>% 
  group_by(position) %>% 
  mutate(
    pos_id = row_number()
  ) %>% 
  ungroup() %>% 
  pivot_wider(
    names_from = position,
    values_from = Understat_Name
  ) %>%
  select(-pos_id) %>% 
  relocate(GK, DEF, MID, FWD)
)
```

```{r GK}
pos <- "GK"
prop <- 1

#main player
gk_maxpoints <- db01c %>%
  group_by(position) %>%
  arrange(desc(avg_points)) %>%
  slice_head(prop = prop) %>%
  ungroup() %>%
  filter(position == pos)

#bench player
gk_minprice <- db01c %>%
  group_by(position) %>%
  arrange(avg_price) %>%
  slice_head(prop = prop) %>%
  ungroup() %>%
  filter(position == pos)

#all players
gk_pool <- gk_maxpoints %>%
  bind_rows(gk_minprice) %>%
  unique()

#db03a <- t(combn(gk_pool$Understat_Name, 2)) #max: 2 players
#saveRDS(db03a, "db03a.rds")

#db03b <- db03a %>%
  na.omit() %>%
  as_tibble() %>%
  mutate("id_gk" = row_number()) %>%
  relocate(id_gk) %>%
  pivot_longer(cols = 2:3,
               names_to = "v",
               values_to = "Understat_Name") %>%
  select(-v) %>%
  left_join(db01c, by = "Understat_Name")

#saveRDS(db03b, "db03b.rds")

#db03c <- db03b %>%
#  group_by(id_gk) %>%
#  mutate(
#    agg_avgpoints = sum(avg_points),
#    avg_wvgpoints = mean(wvg_points),
#    avg_avgminutes = mean(avg_minutes),
#    avg_stdpoints = mean(std_points),
#    agg_avgprice = sum(avg_price),
#    avg_stdinfluence = mean(std_influence),
#    avg_avgXG = mean(avg_xG),
#    avg_avgxA = mean(avg_xA),
#    avg_avgnpxG = mean(avg_npxG),
#    avg_avgxGChain = mean(avg_xGChain),
#    avg_avgxGBuildup = mean(avg_xGBuildup)
#  ) %>%
#  arrange(
#    desc(agg_avgpoints),
#    desc(avg_wvgpoints), #semakin besar, semakin worth it
#    agg_avgprice,
#    desc(avg_avgXG),
#    desc(avg_avgxA),
#    desc(avg_avgminutes),
#    desc(avg_stdpoints)
#  )

#db03c <- db03b %>%
  group_by(id_gk) %>%
  summarise(
    agg_avgpoints = sum(avg_points),
    avg_wvgpoints = mean(wvg_points),
    avg_avgminutes = mean(avg_minutes),
    avg_stdpoints = mean(std_points),
    agg_avgprice = sum(avg_price),
    avg_stdinfluence = mean(std_influence),
    avg_avgXG = mean(avg_xG),
    avg_avgxA = mean(avg_xA),
    avg_avgnpxG = mean(avg_npxG),
    avg_avgxGChain = mean(avg_xGChain),
    avg_avgxGBuildup = mean(avg_xGBuildup)
    ) %>%
  arrange(
    desc(agg_avgpoints),
    desc(avg_wvgpoints), #semakin besar, semakin worth it
    agg_avgprice,
    desc(avg_avgXG),
    desc(avg_avgxA),
    desc(avg_avgminutes),
    desc(avg_stdpoints)
  )

#saveRDS(db03c, "db03c.rds")
  
#db99c <- db03c %>%
#  filter(between(total_avgpoints,
#                 quantile(total_avgpoints, .25),
#                 quantile(total_avgpoints, .75))
#         )

db03d <- db03c %>%
  arrange(desc(agg_avgpoints)) %>%
  filter(agg_avgprice < 10 & agg_avgprice > 8) %>%
  slice_head(n = 5) %>%
  left_join(db03b, by = "id_gk") %>%
  relocate(id_gk, Understat_Name, team) %>%
  select(
    id_gk,
    Understat_Name,
    team,
    avg_points,
    std_points,
    wvg_points,
    avg_price,
    avg_xG,
    avg_xA,
    avg_xGChain,
    avg_xGBuildup,
    agg_avgprice,
    agg_avgpoints,
    avg_stdpoints,
    avg_wvgpoints,
    avg_avgXG,
    avg_avgxA,
    avg_avgxGChain,
    avg_avgxGBuildup
  ) %>%
  arrange(desc(agg_avgpoints),
          desc(avg_wvgpoints))

(
  gk_plot <- db03d %>%
    select(
      id_gk,
      agg_avgprice,
      agg_avgpoints,
      avg_avgxGChain,
      avg_avgxGBuildup
    ) %>%
    group_by(id_gk) %>% 
    slice_head(n=1) %>% 
    ungroup() %>% 
    pivot_longer(
      cols = 2:5,
      names_to = "indicator",
      values_to = "value"
    ) %>%
    ggplot(aes(x = factor(id_gk), y = value)) +
    geom_bar(stat = "identity", aes(fill = factor(id_gk))) +
    #coord_flip() +
    #scale_fill_viridis(discrete = TRUE) +
    #scale_fill_manual(values = wes_palette("Darjeeling1")) +
    scale_fill_manual(values = c("#ef476f","#ffd166","#06d6a0","#118ab2","#073b4c")) +
    egg::theme_article() +
    facet_wrap(~ indicator, ncol = 2, scales = "free") +
    theme(
      legend.position = "none"
    ) +
    labs(
      x = "",
      y = ""
    )
)
```

```{r}
(gk_choice <- db03d %>% filter(id_gk == 55) %>% mutate("position" = "GK"))
```

```{r DEF}
pos <- "DEF"
prop <- 1

#main player
def_maxpoints <- db01c %>%
  group_by(position) %>%
  arrange(desc(avg_points)) %>%
  slice_head(prop = prop) %>%
  ungroup() %>%
  filter(position == pos)

#bench player
def_minprice <- db01c %>%
  group_by(position) %>%
  arrange(avg_price) %>%
  slice_head(prop = prop) %>%
  ungroup() %>%
  filter(position == pos)

#all players
def_pool <- def_maxpoints %>%
  bind_rows(def_minprice) %>%
  unique()

#db04a <- t(combn(def_pool$Understat_Name, 5)) #max: 5 players
#saveRDS(db04a, "db04a.rds")

#db04b <- db04a %>%
  na.omit() %>%
  as_tibble() %>%
  mutate("id_def" = row_number()) %>%
  relocate(id_def) %>%
  pivot_longer(cols = 2:6,
               names_to = "v",
               values_to = "Understat_Name") %>%
  select(-v) %>%
  left_join(db01c, by = "Understat_Name")

#saveRDS(db04b, "db04b.rds")
  
#db04c <- db04b %>%
#  group_by(id_def) %>%
#  mutate(
#    agg_avgpoints = sum(avg_points),
#    avg_wvgpoints = mean(wvg_points),
#    avg_avgminutes = mean(avg_minutes),
#    avg_stdpoints = mean(std_points),
#    agg_avgprice = sum(avg_price),
#    avg_stdinfluence = mean(std_influence),
#    avg_avgXG = mean(avg_xG),
#    avg_avgxA = mean(avg_xA),
#    avg_avgnpxG = mean(avg_npxG),
#    avg_avgxGChain = mean(avg_xGChain),
#    avg_avgxGBuildup = mean(avg_xGBuildup)
#  ) %>%
#  arrange(
#    desc(agg_avgpoints),
#    desc(avg_wvgpoints), #semakin besar, semakin worth it
#    agg_avgprice,
#    desc(avg_avgXG),
#    desc(avg_avgxA),
#    desc(avg_avgminutes),
#    desc(avg_stdpoints)
#  )

#db04c <- db04b %>%
  group_by(id_def) %>%
  summarise(
    agg_avgpoints = sum(avg_points),
    avg_wvgpoints = mean(wvg_points),
    avg_avgminutes = mean(avg_minutes),
    avg_stdpoints = mean(std_points),
    agg_avgprice = sum(avg_price),
    avg_stdinfluence = mean(std_influence),
    avg_avgXG = mean(avg_xG),
    avg_avgxA = mean(avg_xA),
    avg_avgnpxG = mean(avg_npxG),
    avg_avgxGChain = mean(avg_xGChain),
    avg_avgxGBuildup = mean(avg_xGBuildup)
    ) %>%
  arrange(
    desc(agg_avgpoints),
    desc(avg_wvgpoints), #semakin besar, semakin worth it
    agg_avgprice,
    desc(avg_avgXG),
    desc(avg_avgxA),
    desc(avg_avgminutes),
    desc(avg_stdpoints)
  )

#saveRDS(db04c, "db04c.rds")

#db99d <- db04c %>%
#  filter(between(total_avgpoints,
#                 quantile(total_avgpoints, .25),
#                 quantile(total_avgpoints, .75))
#         )

db04d <- db04c %>%
  arrange(desc(agg_avgpoints)) %>%
  filter(agg_avgprice < 30 & agg_avgprice > 29) %>%
  slice_head(n = 5) %>%
  left_join(db04b, by = "id_def") %>%
  relocate(id_def, Understat_Name, team) %>%
  select(
    id_def,
    Understat_Name,
    team,
    avg_points,
    std_points,
    wvg_points,
    avg_price,
    avg_xG,
    avg_xA,
    avg_xGChain,
    avg_xGBuildup,
    agg_avgprice,
    agg_avgpoints,
    avg_stdpoints,
    avg_wvgpoints,
    avg_avgXG,
    avg_avgxA,
    avg_avgxGChain,
    avg_avgxGBuildup
  ) %>%
  arrange(desc(agg_avgpoints),
          desc(avg_wvgpoints),
          desc(avg_avgXG),
          desc(avg_avgxA))

(
  def_plot <- db04d %>%
    select(
      id_def,
      agg_avgprice,
      agg_avgpoints,
      avg_avgXG,
      avg_avgxA
    ) %>%
    group_by(id_def) %>% 
    slice_head(n=1) %>% 
    ungroup() %>% 
    pivot_longer(
      cols = 2:5,
      names_to = "indicator",
      values_to = "value"
    ) %>%
    ggplot(aes(x = factor(id_def), y = value)) +
    geom_bar(stat = "identity", aes(fill = factor(id_def))) +
    #coord_flip() +
    #scale_fill_viridis(discrete = TRUE) +
    #scale_fill_manual(values = wes_palette("Darjeeling1")) +
    scale_fill_manual(values = c("#ef476f","#ffd166","#06d6a0","#118ab2","#073b4c")) +
    egg::theme_article() +
    facet_wrap(~ indicator, ncol = 2, scales = "free") +
    theme(
      legend.position = "none"
    ) +
    labs(
      x = "",
      y = ""
    )
)

```

```{r}
(def_choice <- db04d %>% filter(id_def == 29318) %>% mutate("position" = "DEF"))
```

```{r MID}
pos <- "MID"
prop <- 1

#main player
mid_maxpoints <- db01c %>%
  group_by(position) %>%
  arrange(desc(avg_points)) %>%
  slice_head(prop = prop) %>%
  ungroup() %>%
  filter(position == pos)

#bench player
mid_minprice <- db01c %>%
  group_by(position) %>%
  arrange(avg_price) %>%
  slice_head(prop = prop) %>%
  ungroup() %>%
  filter(position == pos)

#all players
mid_pool <- mid_maxpoints %>%
  bind_rows(mid_minprice) %>%
  unique()

#db05a <- t(combn(mid_pool$Understat_Name, 5)) #max: 5 players
#saveRDS(db05a, "db05a.rds")

#db05b <- db05a %>%
  na.omit() %>%
  as_tibble() %>%
  mutate("id_mid" = row_number()) %>%
  relocate(id_mid) %>%
  pivot_longer(cols = 2:6,
               names_to = "v",
               values_to = "Understat_Name") %>%
  select(-v) %>%
  left_join(db01c, by = "Understat_Name")

#saveRDS(db05b, "db05b.rds")
  
#db05c <- db05b %>%
#  group_by(id_mid) %>%
#  mutate(
#    agg_avgpoints = sum(avg_points),
#    avg_wvgpoints = mean(wvg_points),
#    avg_avgminutes = mean(avg_minutes),
#    avg_stdpoints = mean(std_points),
#    agg_avgprice = sum(avg_price),
#    avg_stdinfluence = mean(std_influence),
#    avg_avgXG = mean(avg_xG),
#    avg_avgxA = mean(avg_xA),
#    avg_avgnpxG = mean(avg_npxG),
#    avg_avgxGChain = mean(avg_xGChain),
#    avg_avgxGBuildup = mean(avg_xGBuildup)
#  ) %>%
#  arrange(
#    desc(agg_avgpoints),
#    desc(avg_wvgpoints), #semakin besar, semakin worth it
#    agg_avgprice,
#    desc(avg_avgXG),
#    desc(avg_avgxA),
#    desc(avg_avgminutes),
#    desc(avg_stdpoints)
#  )

#db05c <- db05b %>%
  group_by(id_mid) %>%
  summarise(
    agg_avgpoints = sum(avg_points),
    avg_wvgpoints = mean(wvg_points),
    avg_avgminutes = mean(avg_minutes),
    avg_stdpoints = mean(std_points),
    agg_avgprice = sum(avg_price),
    avg_stdinfluence = mean(std_influence),
    avg_avgXG = mean(avg_xG),
    avg_avgxA = mean(avg_xA),
    avg_avgnpxG = mean(avg_npxG),
    avg_avgxGChain = mean(avg_xGChain),
    avg_avgxGBuildup = mean(avg_xGBuildup)
    ) %>%
  arrange(
    desc(agg_avgpoints),
    desc(avg_wvgpoints), #semakin besar, semakin worth it
    agg_avgprice,
    desc(avg_avgXG),
    desc(avg_avgxA),
    desc(avg_avgminutes),
    desc(avg_stdpoints)
  )

#saveRDS(db05c, "db05c.rds")
  
#db99e <- db05c %>%
#  filter(between(total_avgpoints,
#                 quantile(total_avgpoints, .25),
#                 quantile(total_avgpoints, .75))
#         )

db05d <- db05c %>%
  arrange(desc(agg_avgpoints)) %>%
  filter(agg_avgprice < 40 & agg_avgprice > 39) %>%
  slice_head(n = 5) %>%
  left_join(db05b, by = "id_mid") %>%
  relocate(id_mid, Understat_Name, team) %>%
  select(
    id_mid,
    Understat_Name,
    team,
    avg_points,
    std_points,
    wvg_points,
    avg_price,
    avg_xG,
    avg_xA,
    avg_xGChain,
    avg_xGBuildup,
    agg_avgprice,
    agg_avgpoints,
    avg_stdpoints,
    avg_wvgpoints,
    avg_avgXG,
    avg_avgxA,
    avg_avgxGChain,
    avg_avgxGBuildup
  ) %>%
  arrange(desc(agg_avgpoints),
          desc(avg_wvgpoints),
          desc(avg_avgXG),
          desc(avg_avgxA))

(
  mid_plot <- db05d %>%
    select(
      id_mid,
      agg_avgprice,
      agg_avgpoints,
      avg_avgXG,
      avg_avgxA
    ) %>%
    group_by(id_mid) %>% 
    slice_head(n=1) %>% 
    ungroup() %>% 
    pivot_longer(
      cols = 2:5,
      names_to = "indicator",
      values_to = "value"
    ) %>%
    ggplot(aes(x = factor(id_mid), y = value)) +
    geom_bar(stat = "identity", aes(fill = factor(id_mid))) +
    #coord_flip() +
    #scale_fill_viridis(discrete = TRUE) +
    #scale_fill_manual(values = wes_palette("Darjeeling1")) +
    scale_fill_manual(values = c("#ef476f","#ffd166","#06d6a0","#118ab2","#073b4c")) +
    egg::theme_article() +
    facet_wrap(~ indicator, ncol = 2, scales = "free") +
    theme(
      legend.position = "none"
    ) +
    labs(
      x = "",
      y = ""
    )
)

```

```{r}
(mid_choice <- db05d %>% filter(id_mid == 613) %>% mutate("position" = "MID"))
```

```{r FWD}
pos <- "FWD"
prop <- 1

#main player
fwd_maxpoints <- db01c %>%
  group_by(position) %>%
  arrange(desc(avg_points)) %>%
  slice_head(prop = prop) %>%
  ungroup() %>%
  filter(position == pos)

#bench player
fwd_minprice <- db01c %>%
  group_by(position) %>%
  arrange(avg_price) %>%
  slice_head(prop = prop) %>%
  ungroup() %>%
  filter(position == pos)

#all players
fwd_pool <- fwd_maxpoints %>%
  bind_rows(fwd_minprice) %>%
  unique()

#db06a <- t(combn(fwd_pool$Understat_Name, 3)) #max: 3 players

#saveRDS(db06a, "db06a.rds")

#db06b <- db06a %>%
  na.omit() %>%
  as_tibble() %>%
  mutate("id_fwd" = row_number()) %>%
  relocate(id_fwd) %>%
  pivot_longer(cols = 2:4,
               names_to = "v",
               values_to = "Understat_Name") %>%
  select(-v) %>%
  left_join(db01c, by = "Understat_Name")

#saveRDS(db06b, "db06b.rds")

#db06c <- db06b %>%
#  group_by(id_fwd) %>%
#  mutate(
#    agg_avgpoints = sum(avg_points),
#    avg_wvgpoints = mean(wvg_points),
#    avg_avgminutes = mean(avg_minutes),
#    avg_stdpoints = mean(std_points),
#    agg_avgprice = sum(avg_price),
#    avg_stdinfluence = mean(std_influence),
#    avg_avgXG = mean(avg_xG),
#    avg_avgxA = mean(avg_xA),
#    avg_avgnpxG = mean(avg_npxG),
#    avg_avgxGChain = mean(avg_xGChain),
#    avg_avgxGBuildup = mean(avg_xGBuildup)
#  ) %>%
#  arrange(
#    desc(agg_avgpoints),
#    desc(avg_wvgpoints), #semakin besar, semakin worth it
#    agg_avgprice,
#    desc(avg_avgXG),
#    desc(avg_avgxA),
#    desc(avg_avgminutes),
#    desc(avg_stdpoints)
#  )

#db06c <- db06b %>%
  group_by(id_fwd) %>%
  summarise(
    agg_avgpoints = sum(avg_points),
    avg_wvgpoints = mean(wvg_points),
    avg_avgminutes = mean(avg_minutes),
    avg_stdpoints = mean(std_points),
    agg_avgprice = sum(avg_price),
    avg_stdinfluence = mean(std_influence),
    avg_avgXG = mean(avg_xG),
    avg_avgxA = mean(avg_xA),
    avg_avgnpxG = mean(avg_npxG),
    avg_avgxGChain = mean(avg_xGChain),
    avg_avgxGBuildup = mean(avg_xGBuildup)
    ) %>%
  arrange(
    desc(agg_avgpoints),
    desc(avg_wvgpoints), #semakin besar, semakin worth it
    agg_avgprice,
    desc(avg_avgXG),
    desc(avg_avgxA),
    desc(avg_avgminutes),
    desc(avg_stdpoints)
  )

#saveRDS(db06c, "db06c.rds")

#db99f <- db06c %>%
#  filter(between(total_avgpoints,
#                 quantile(total_avgpoints, .25),
#                 quantile(total_avgpoints, .75))
#         )

db06d <- db06c %>%
  arrange(desc(agg_avgpoints)) %>%
  filter(agg_avgprice < 20 & agg_avgprice > 19) %>%
  slice_head(n = 5) %>%
  left_join(db06b, by = "id_fwd") %>%
  relocate(id_fwd, Understat_Name, team) %>%
  select(
    id_fwd,
    Understat_Name,
    team,
    avg_points,
    std_points,
    wvg_points,
    avg_price,
    avg_xG,
    avg_xA,
    avg_xGChain,
    avg_xGBuildup,
    agg_avgprice,
    agg_avgpoints,
    avg_stdpoints,
    avg_wvgpoints,
    avg_avgXG,
    avg_avgxA,
    avg_avgxGChain,
    avg_avgxGBuildup
  ) %>%
  arrange(desc(agg_avgpoints),
          desc(avg_wvgpoints),
          desc(avg_avgXG),
          desc(avg_avgxA))

(
  fwd_plot <- db06d %>%
    select(
      id_fwd,
      agg_avgprice,
      agg_avgpoints,
      avg_avgXG,
      avg_avgxA
    ) %>%
    group_by(id_fwd) %>% 
    slice_head(n=1) %>% 
    ungroup() %>% 
    pivot_longer(
      cols = 2:5,
      names_to = "indicator",
      values_to = "value"
    ) %>%
    ggplot(aes(x = factor(id_fwd), y = value)) +
    geom_bar(stat = "identity", aes(fill = factor(id_fwd))) +
    #coord_flip() +
    #scale_fill_viridis(discrete = TRUE) +
    #scale_fill_manual(values = wes_palette("Darjeeling1")) +
    scale_fill_manual(values = c("#ef476f","#ffd166","#06d6a0","#118ab2","#073b4c")) +
    egg::theme_article() +
    facet_wrap(~ indicator, ncol = 2, scales = "free") +
    theme(
      legend.position = "none"
    ) +
    labs(
      x = "",
      y = ""
    )
)

```

```{r}
(fwd_choice <- db06d %>% filter(id_fwd == 831) %>% mutate("position" = "FWD"))
```

```{r}
(belutlistrik_squad <- (gk_choice %>% rename("id" = id_gk)) %>%
   bind_rows((def_choice %>% rename("id" = id_def)),
             (mid_choice %>% rename("id" = id_mid)),
             (fwd_choice %>% rename("id" = id_fwd))
   ) %>% 
   mutate(
     "formid" = row_number()
   ) %>% 
   relocate(id, formid, Understat_Name, position) %>% 
   mutate(
     Understat_Name = recode(Understat_Name, "Trent Alexander-Arnold" = "Trent")
   )
 )
```

```{r}
(
  belutlistrik_select <- belutlistrik_squad %>%
    filter(position != "GK") %>%
    select(
      Understat_Name,
      position,
      avg_points,
      avg_price,
      wvg_points,
      avg_xG,
      avg_xA,
      avg_xGChain,
      avg_xGBuildup,
      std_points
    ) %>%
    pivot_longer(
      cols = 3:10,
      names_to = "indicator",
      values_to = "value"
    ) %>%
    #mutate(
    #  "indicator" = as.factor(indicator),
    #  "Understat_Name" = tidytext::reorder_within(Understat_Name, value, indicator)
    #    ) %>%
    ggplot(aes(
      x = reorder_within(Understat_Name, value, indicator),
      y = value,
      fill = factor(position)
    )) +
    #geom_col(show.legend = FALSE) +
    geom_col() +
    #geom_bar(stat = "identity", aes(fill = factor(position))) +
    coord_flip() +
    scale_x_reordered() +
    #scale_fill_viridis(discrete = TRUE) +
    #scale_fill_manual(values = wes_palette("Darjeeling1")) +
    scale_fill_manual(values = c("#ef476f", "#ffd166", "#06d6a0")) +
    egg::theme_article() +
    facet_wrap( ~ indicator, ncol = 4, scales = "free_y") +
    theme(legend.position = "top",
          legend.title = element_blank()) +
    labs(x = "",
         y = "")
  #guides(fill = guide_legend("Position:"))
)
```

```{r}
(belutlistrik_options <- belutlistrik_squad %>% 
   mutate(
     "form352" = ifelse(formid %in% c(2, 6, 7, 15), "bench", "play"),
     "form442" = ifelse(formid %in% c(2, 7, 12, 15), "bench", "play"),
     "form343" = ifelse(formid %in% c(2, 6, 7, 12), "bench", "play")
   ) %>% 
   relocate(id, formid, form442, form343, form352, Understat_Name) 
)
```

```{r}
(for352 <- tibble(
  x = c(98, 98, 83, 83, 83, 89 ,80, 68, 68, 68, 68, 68, 53, 53, 71),
  y = c(50, 110, 25, 50, 75, 110, 110, 10, 30, 50, 70, 90, 37.5, 62.5, 110),
  formid = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)
))

(for442 <- tibble(
  x = c(98, 98, 83, 83, 83, 83, 89 ,68, 68, 68, 68, 80, 53, 53, 71),
  y = c(50, 110, 20, 40, 60, 80, 110, 20, 40, 60, 80, 110, 37.5, 62.5, 110),
  formid = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)
))

(for343 <- tibble(
  x = c(98, 98, 83, 83, 83, 89, 80, 68, 68, 68, 68, 71, 53, 53, 53),
  y = c(50, 110, 25, 50, 75, 110, 110, 20, 40, 60, 80, 110, 25, 50, 75),
  formid = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)
))
```

```{r}
(
  belutlistrik_442 <- belutlistrik_options %>%
    select(formid, form442, Understat_Name) %>%
    right_join(for442, by = "formid")
)

(
  belutlistrik_343 <- belutlistrik_options %>%
    select(formid, form343, Understat_Name) %>%
    right_join(for343, by = "formid")
)
```

```{r}
(
  belutlistrik <- ggplot(belutlistrik_442) + #change
    annotate_pitch(
      colour = "white",
      fill   = "#e0e2db",
      limits = FALSE
    ) +
    geom_point(
      aes(x = x, y = 100 - y, fill = factor(form442)), #change
      shape = 21,
      size = 5
    ) +
    scale_fill_manual(values = c("play" = "#8b2635", "bench" = "#2e3532")) +
    geom_text_repel(
      aes(
        x = x,
        y = 100 - y,
        label = stringr::str_wrap(Understat_Name, 10),
        color = factor(form442) #change
      ),
      direction = "y",
      nudge_x = -4,
      segment.colour = NA,
      size = 3,
      #box.padding = unit(-2.5, "lines")
    ) +
    scale_color_manual(values = c("play" = "#8b2635", "bench" = "#2e3532")) +
    theme_pitch() +
    theme(
      panel.background = element_rect(fill = "#e0e2db"),
      legend.position = "none",
      plot.title = element_text(hjust = 0, size = 18,
                                face = "bold"),
      plot.subtitle = element_text(hjust = 0, size = 14),
    ) +
    coord_flip(xlim = c(49, 101),
               ylim = c(-12, 112)) +
    ggtitle("Belut Listrik FC",
            "instagram/arifpras")
)

#belutlistrik
```

```{r}
# Removes all items in Environment!
rm(list = ls())
ls()
```

