---
title: "20220617_fpl"
author: "Arif P. Sulistiono / @arifpras"
date: '2022-06-17'
output: html_document
---

```{r}
# Remove all items in Environment!
rm(list = ls())
ls()

# Load packages
pacman::p_load(tidyverse, data.table, readxl, writexl, glue, wesanderson,
               RColorBrewer, viridis, ggrepel, ggthemes, ggsci, mFilter,
               quantmod, corrplot, cowplot, readstata13, readr, knitr, 
               kableExtra, stargazer, parameters, colorspace, dendextend,
               ggdendro, purrr, cluster, plotly, DescTools, factoextra, 
               grid, gridExtra)

options(tz = "Europe/London")

# Working directory
setwd("~/OneDrive - The University of Nottingham/BB_SideProject/2022FPL")
```

```{r}
db01 <- read.csv("20220617_db.csv")
```

```{r}
db02 <- db01 %>% 
  select(player, position) %>% 
  as_tibble() %>% 
  group_by(position) %>% 
  mutate(
    id = row_number()
  ) %>% 
  ungroup() %>% 
  pivot_wider(
    names_from = position,
    values_from = player
  )
  
```

```{r}
db03 <- crossing(
  db02$GK,
  db02$GK,
  db02$DEF,
  db02$DEF,
  db02$DEF,
  db02$DEF,
  db02$DEF,
  db02$MID,
  db02$MID,
  db02$MID,
  db02$MID,
  db02$MID,
  db02$FWD,
  db02$FWD,
  db02$FWD
)
```

```{r}
db03 <- tidyr::expand_grid(
  db02$GK,
  db02$GK,
  db02$DEF,
  db02$DEF,
  db02$DEF
)
```

```{r}
#https://stackoverflow.com/questions/11388359/unique-combination-of-all-elements-from-two-or-more-vectors

db03 <- data.table::CJ(
  db02$GK,
  db02$GK,
  db02$DEF,
  db02$DEF,
  db02$DEF,
  db02$DEF,
  db02$DEF,
  db02$MID,
  db02$MID,
  db02$MID,
  db02$MID,
  db02$MID,
  db02$FWD,
  db02$FWD,
  db02$FWD, unique = TRUE
)
```

```{r GK}
#https://stackoverflow.com/questions/12245213/how-to-generate-all-possible-combinations-of-vectors-without-caring-for-order

pos <- "GK"
prop <- 0.25

gk_maxpoints <- db01 %>%
  group_by(position) %>%
  arrange(desc(avg_points)) %>%
  slice_head(prop = prop) %>%
  ungroup() %>%
  filter(position == pos)

gk_minprice <- db01 %>%
  group_by(position) %>%
  arrange(avg_price) %>%
  slice_head(prop = prop) %>%
  ungroup() %>%
  filter(position == pos)

gk_pool <- gk_maxpoints %>%
  bind_rows(gk_minprice) %>%
  unique()

db07 <- t(combn(gk_pool$player, 2))
db07 <- db07 %>%
  na.omit() %>%
  as_tibble() %>%
  mutate("id_gk" = row_number()) %>%
  relocate(id_gk) %>%
  pivot_longer(cols = 2:3,
               names_to = "v",
               values_to = "player") %>%
  select(-v) %>%
  left_join(db01, by = "player")

db08 <- db07 %>%
  group_by(id_gk) %>%
  mutate(
    total_avgpoints = sum(avg_points),
    wghwmean_avgpoints = weighted.mean(avg_points, avg_price),
    avg_avgminutes = mean(avg_minutes),
    avg_stdevpoints = mean(stdev_totalpoints),
    total_avgprice = sum(avg_price),
    avg_stdevinfluence = mean(stdev_influence)
  ) %>%
  arrange(
    desc(total_avgpoints),
    desc(wghwmean_avgpoints),
    #semakin besar, semakin worth it
    total_avgprice,
    desc(avg_avgminutes),
    desc(avg_stdevpoints),
    avg_stdevinfluence
  )

db09 <- db07 %>%
  group_by(id_gk) %>%
  summarise(
    total_avgpoints = sum(avg_points),
    wghwmean_avgpoints = weighted.mean(avg_points, avg_price),
    avg_avgminutes = mean(avg_minutes),
    avg_stdevpoints = mean(stdev_totalpoints),
    total_avgprice = sum(avg_price),
    avg_stdevinfluence = mean(stdev_influence)
  ) %>%
  arrange(
    desc(total_avgpoints),
    desc(wghwmean_avgpoints),
    #semakin besar, semakin worth it
    total_avgprice,
    desc(avg_avgminutes),
    desc(avg_stdevpoints),
    avg_stdevinfluence
  )

#db10 <- db09 %>%
#  filter(between(total_avgpoints,
#                 quantile(total_avgpoints, .25),
#                 quantile(total_avgpoints, .75))
#         )

db10 <- db09 %>%
  arrange(desc(total_avgpoints)) %>%
  filter(total_avgprice < 10 & total_avgprice > 8) %>%
  slice_head(n = 5) %>%
  left_join(db07, by = "id_gk") %>%
  relocate(id_gk, player, team) %>%
  select(
    id_gk,
    player,
    team,
    avg_points,
    stdev_totalpoints,
    avg_price,
    total_avgprice,
    total_avgpoints,
    wghwmean_avgpoints
  ) %>%
  arrange(desc(total_avgpoints),
          desc(wghwmean_avgpoints))
```

```{r DEF}
pos <- "DEF"
prop <- 0.25

def_maxpoints <- db01 %>%
  group_by(position) %>%
  arrange(desc(avg_points)) %>%
  slice_head(prop = prop) %>%
  ungroup() %>%
  filter(position == pos)

def_minprice <- db01 %>%
  group_by(position) %>%
  arrange(avg_price) %>%
  slice_head(prop = prop) %>%
  ungroup() %>%
  filter(position == pos)

def_pool <- def_maxpoints %>%
  bind_rows(def_minprice) %>%
  unique()

db11 <- t(combn(def_pool$player, 5))
db11 <- db11 %>%
  na.omit() %>%
  as_tibble() %>%
  mutate("id_def" = row_number()) %>%
  relocate(id_def) %>%
  pivot_longer(cols = 2:6,
               names_to = "v",
               values_to = "player") %>%
  select(-v) %>%
  left_join(db01, by = "player")

db12 <- db11 %>%
  group_by(id_def) %>%
  mutate(
    total_avgpoints = sum(avg_points),
    wghwmean_avgpoints = weighted.mean(avg_points, avg_price),
    avg_avgminutes = mean(avg_minutes),
    avg_stdevpoints = mean(stdev_totalpoints),
    total_avgprice = sum(avg_price),
    avg_stdevinfluence = mean(stdev_influence)
  ) %>%
  arrange(
    desc(total_avgpoints),
    desc(wghwmean_avgpoints),
    #semakin besar, semakin worth it
    total_avgprice,
    desc(avg_avgminutes),
    desc(avg_stdevpoints),
    avg_stdevinfluence
  )

db13 <- db11 %>%
  group_by(id_def) %>%
  summarise(
    total_avgpoints = sum(avg_points),
    wghwmean_avgpoints = weighted.mean(avg_points, avg_price),
    avg_avgminutes = mean(avg_minutes),
    avg_stdevpoints = mean(stdev_totalpoints),
    total_avgprice = sum(avg_price),
    avg_stdevinfluence = mean(stdev_influence)
  ) %>%
  arrange(
    desc(total_avgpoints),
    desc(wghwmean_avgpoints),
    #semakin besar, semakin worth it
    total_avgprice,
    desc(avg_avgminutes),
    desc(avg_stdevpoints),
    avg_stdevinfluence
  )

#db14 <- db13 %>%
#  filter(between(total_avgpoints,
#                 quantile(total_avgpoints, .45),
#                 quantile(total_avgpoints, .55))
#         )

db14 <- db13 %>%
  arrange(desc(total_avgpoints)) %>%
  filter(total_avgprice < 30 & total_avgprice > 29) %>%
  slice_head(n = 5) %>%
  left_join(db11, by = "id_def") %>%
  relocate(id_def, player, team) %>%
  select(
    id_def,
    player,
    team,
    avg_points,
    stdev_totalpoints,
    avg_price,
    total_avgprice,
    total_avgpoints,
    wghwmean_avgpoints
  ) %>%
  arrange(desc(total_avgpoints),
          desc(wghwmean_avgpoints))
```

```{r MID}
pos <- "MID"
prop <- 0.25

mid_maxpoints <- db01 %>%
  group_by(position) %>%
  arrange(desc(avg_points)) %>%
  slice_head(prop = prop) %>%
  ungroup() %>%
  filter(position == pos)

mid_minprice <- db01 %>%
  group_by(position) %>%
  arrange(avg_price) %>%
  slice_head(prop = prop) %>%
  ungroup() %>%
  filter(position == pos)

mid_pool <- mid_maxpoints %>%
  bind_rows(mid_minprice) %>%
  unique()

db15 <- t(combn(mid_pool$player, 5))
db15 <- db15 %>%
  na.omit() %>%
  as_tibble() %>%
  mutate("id_mid" = row_number()) %>%
  relocate(id_mid) %>%
  pivot_longer(cols = 2:6,
               names_to = "v",
               values_to = "player") %>%
  select(-v) %>%
  left_join(db01, by = "player")

db16 <- db15 %>%
  group_by(id_mid) %>%
  mutate(
    total_avgpoints = sum(avg_points),
    wghwmean_avgpoints = weighted.mean(avg_points, avg_price),
    avg_avgminutes = mean(avg_minutes),
    avg_stdevpoints = mean(stdev_totalpoints),
    total_avgprice = sum(avg_price),
    avg_stdevinfluence = mean(stdev_influence)
  ) %>%
  arrange(
    desc(total_avgpoints),
    desc(wghwmean_avgpoints),
    #semakin besar, semakin worth it
    total_avgprice,
    desc(avg_avgminutes),
    desc(avg_stdevpoints),
    avg_stdevinfluence
  )

db17 <- db15 %>%
  group_by(id_mid) %>%
  summarise(
    total_avgpoints = sum(avg_points),
    wghwmean_avgpoints = weighted.mean(avg_points, avg_price),
    avg_avgminutes = mean(avg_minutes),
    avg_stdevpoints = mean(stdev_totalpoints),
    total_avgprice = sum(avg_price),
    avg_stdevinfluence = mean(stdev_influence)
  ) %>%
  arrange(
    desc(total_avgpoints),
    desc(wghwmean_avgpoints),
    #semakin besar, semakin worth it
    total_avgprice,
    desc(avg_avgminutes),
    desc(avg_stdevpoints),
    avg_stdevinfluence
  )

#db18 <- db17 %>%
#  filter(between(total_avgpoints,
#                 quantile(total_avgpoints, .45),
#                 quantile(total_avgpoints, .55))
#         )

db18 <- db17 %>%
  arrange(desc(total_avgpoints)) %>%
  filter(total_avgprice < 40 & total_avgprice > 39) %>%
  slice_head(n = 5) %>%
  left_join(db15, by = "id_mid") %>%
  relocate(id_mid, player, team) %>%
  select(
    id_mid,
    player,
    team,
    avg_points,
    stdev_totalpoints,
    avg_price,
    total_avgprice,
    total_avgpoints,
    wghwmean_avgpoints
  ) %>%
  arrange(desc(total_avgpoints),
          desc(wghwmean_avgpoints))
```

```{r FWD}
pos <- "FWD"
prop <- 0.25

fwd_maxpoints <- db01 %>%
  group_by(position) %>% 
  arrange(desc(avg_points)) %>% 
  slice_head(prop = prop) %>% 
  ungroup() %>%
  filter(position == pos)

fwd_minprice <- db01 %>%
  group_by(position) %>% 
  arrange(avg_price) %>%   
  slice_head(prop = prop) %>% 
  ungroup() %>% 
  filter(position == pos)

fwd_pool <- fwd_maxpoints %>% 
  bind_rows(fwd_minprice) %>% 
  unique()
 
db19 <- t(combn(fwd_pool$player,3))
db19 <- db19 %>% 
  na.omit() %>% 
  as_tibble() %>% 
  mutate(
    "id_fwd" = row_number()
  ) %>%
  relocate(id_fwd) %>% 
  pivot_longer(
    cols = 2:4,
    names_to = "v",
    values_to = "player"
  ) %>% 
  select(-v) %>% 
  left_join(
    db01, by = "player"
  )

db20 <- db19 %>% 
  group_by(id_fwd) %>% 
  mutate(
    total_avgpoints = sum(avg_points),
    wghwmean_avgpoints = weighted.mean(avg_points, avg_price),
    avg_avgminutes = mean(avg_minutes),
    avg_stdevpoints = mean(stdev_totalpoints),
    total_avgprice = sum(avg_price),
    avg_stdevinfluence = mean(stdev_influence)
  ) %>% 
    arrange(
    desc(total_avgpoints),
    desc(wghwmean_avgpoints), #semakin besar, semakin worth it
    total_avgprice,
    desc(avg_avgminutes),
    desc(avg_stdevpoints),
    avg_stdevinfluence
  )

db21 <- db19 %>% 
  group_by(id_fwd) %>% 
  summarise(
    total_avgpoints = sum(avg_points),
    wghwmean_avgpoints = weighted.mean(avg_points, avg_price),
    avg_avgminutes = mean(avg_minutes),
    avg_stdevpoints = mean(stdev_totalpoints),
    total_avgprice = sum(avg_price),
    avg_stdevinfluence = mean(stdev_influence)
  ) %>% 
  arrange(
    desc(total_avgpoints),
    desc(wghwmean_avgpoints), #semakin besar, semakin worth it
    total_avgprice,
    desc(avg_avgminutes),
    desc(avg_stdevpoints),
    avg_stdevinfluence
  )

#db22 <- db21 %>% 
#  filter(between(total_avgpoints, 
#                 quantile(total_avgpoints, .45), 
#                 quantile(total_avgpoints, .55))
#         )

db22 <- db21 %>%
  arrange(desc(total_avgpoints)) %>%
  filter(total_avgprice < 20 & total_avgprice > 19) %>%
  slice_head(n = 5) %>%
  left_join(db19, by = "id_fwd") %>%
  relocate(id_fwd, player, team) %>%
  select(
    id_fwd,
    player,
    team,
    avg_points,
    stdev_totalpoints,
    avg_price,
    total_avgprice,
    total_avgpoints,
    wghwmean_avgpoints
  ) %>%
  arrange(desc(total_avgpoints),
          desc(wghwmean_avgpoints))
```

```{r}
#https://torvaney.github.io/ggsoccer/reference/annotate_pitch.html
```

```{r}
# install.packages("remotes")
#remotes::install_github("torvaney/ggsoccer")

library(ggsoccer)
```

```{r FORM}
blfc <-
  data.frame(
    x = c(98, 83, 83, 83, 68, 68, 68, 68, 68, 53, 53, 98, 90, 82, 74),
    y = c(50, 25, 50, 75, 10, 30, 50, 70, 90, 37.5, 62.5, 110, 110, 110, 110),
    p = c(
      "Martinez",
      "TAA",
      "Cancelo",
      "R.Dias",
      "Salah",
      "Son",
      "Kulusevski",
      "Saka",
      "Bruno G.",
      "Watkins",
      "Toney",
      "Sanchez",
      "Cucurella",
      "Jansson",
      "Dennis"
    ),
    s = c(
      "main",
      "main",
      "main",
      "main",
      "main",
      "main",
      "main",
      "main",
      "main",
      "main",
      "main",
      "bench",
      "bench",
      "bench",
      "bench"
    )
  )

#https://r-charts.com/colors/

(
  plot01 <- ggplot(blfc) +
    annotate_pitch(
      colour = "white",
      fill   = "#e0e2db",
      limits = FALSE
    ) +
    geom_point(
      aes(x = x, y = 100 - y, fill = factor(s)),
      shape = 21,
      size = 10
    ) +
    scale_fill_manual(values = c("main" = "#8b2635", "bench" = "#2e3532")) +
    geom_text_repel(
      aes(
        x = x,
        y = 100 - y,
        label = p,
        color = factor(s)
      ),
      direction = "y",
      nudge_x = -2.5,
      segment.colour = NA,
      size = 8
    ) +
    scale_color_manual(values = c("main" = "#8b2635", "bench" = "#2e3532")) +
    theme_pitch() +
    theme(
      panel.background = element_rect(fill = "#e0e2db"),
      legend.position = "none",
      plot.title = element_text(hjust = 0, size = 22,
                                face = "bold"),
      plot.subtitle = element_text(hjust = 0, size = 20),
    ) +
    coord_flip(xlim = c(49, 101),
               ylim = c(-12, 112)) +
    ggtitle("Belut Listrik FC",
            "instagram/arifpras")
)
```

